Fix trunc instruction
rhysd/wain pull request #14
Opened 2020-05-25 14:59 UTC by kariya-mitsuru

The instruction `inn.trunc_fmm_sx` should cause trap if source value
cannot be represented by target type.

Note: The old implementations of cast functions are renamed and
preserved for future use.  (Wasm 1.1 has the instruction
`inn.trunc_sat_fmm_sx` that should use these functions.)

Passed new 75 tests.

**before**
```
End ".../wain/spec-test/wasm-testsuite/conversions.wast":
  total: 436, passed: 369, failed: 67, skipped: 0

End ".../wain/spec-test/wasm-testsuite/traps.wast":
  total: 37, passed: 29, failed: 8, skipped: 0

Results of 76 files:
  total: 19740, passed: 19046, failed: 498, skipped: 196
```

**after**
```
End ".../wain/spec-test/wasm-testsuite/conversions.wast":
  total: 436, passed: 436, failed: 0, skipped: 0

End ".../wain/spec-test/wasm-testsuite/traps.wast":
  total: 37, passed: 37, failed: 0, skipped: 0

Results of 76 files:
  total: 19740, passed: 19121, failed: 423, skipped: 196
```

2020-05-25 15:04 UTC, kariya-mitsuru commented
すみません、一応この形でプルリクしたのですが、`float_to_int` マクロが条件を自動判別することに注力しすぎて、あまりにも技巧的過ぎる気もしています…
マクロの引数を 1 つ増やして手動で選択する方法もあるのですが、そちらの方がいいですかね…

2020-05-25 15:42 UTC, rhysd commented
ありがとうございます！やらないといけないと思いつつそのままになってた箇所なので助かります．明日コードを見させてください．

2020-05-27 15:08 UTC, rhysd requested changes
すみません，昨日プルリク全部見きれなかったので，今日になってしまいました．

2020-05-27 15:08 UTC, rhysd commented on wain-exec/src/cast.rs
> +            }
マクロを1度しか使ってないので，マクロにしなくて良いかなと思います．また，`$min != $min - 1.0` は定数式なので，`const` で定数にしておいてもらえるとコンパイル時にこの条件分岐が消えることが確実になって良さそうです

```rust
const REPRESENTS_MIN_EXACTLY: bool = MIN != MIN - 1.0;

let lt = if REPRESENTS_MIN_EXACTLY {
    MIN - 1.0 < f
} else {
    MIN <= f
};

if lt && f < MAX + 1.0 {
    Some(f as $int)
} else {
    None
}
```

2020-05-27 15:08 UTC, rhysd commented on wain-exec/src/cast.rs
> +        fn nextafter(self, _: Self) -> Self;
単語の間は `_` で区切っておいていただけると．

```suggestion
        fn next_after(self, _: Self) -> Self;
```

2020-05-27 15:40 UTC, rhysd commented on wain-exec/src/cast.rs
> +        }
これは `o` は origin で，origin 方向に 1bit 分近い数を返すメソッドで良いですよね？

2020-05-27 15:42 UTC, kariya-mitsuru commented on wain-exec/src/cast.rs
> +        }
はい、そうです。
ちょっと（だいぶ）手抜きですが、テスト用ならこれぐらいでいいかな、と…

2020-05-27 15:44 UTC, kariya-mitsuru commented on wain-exec/src/cast.rs
> +        }
ホントは Rust にホンモノの [`nextafter`](https://cpprefjp.github.io/reference/cmath/nextafter.html) があったら使いたかったんですが、どうもなさそうだったので…

2020-05-27 15:47 UTC, rhysd commented on wain-exec/src/cast.rs
> +            let gt_min = if MIN != MIN - 1.0 {
自分の理解を確認しておきたいのですが，`MIN != MIN - 1.0` が成り立つのって，ソース側 `fN` のビット幅 N がターゲット側 `iM` もしくは `uM` のビット幅 M より大きいときだけという理解で良いでしょうか？

2020-05-27 15:48 UTC, rhysd commented on wain-exec/src/cast.rs
> +        }
あ，なるほど math.h 由来の名前でしたか．はい，挙動の確認をしたかっただけなので，実装的にはこれで問題ないと思います :+1:

2020-05-27 15:58 UTC, kariya-mitsuru commented on wain-exec/src/cast.rs
> +            let gt_min = if MIN != MIN - 1.0 {
はい、だいたいそんな感じです。
より厳密に言うと、`iM` の場合は `fN::MANTISSA_DIGITS >= M` の場合で、`uM` の場合は常に成り立ちます。（`MIN` が `0` なので）
ただ、`M` と `N` はどうせ `32` と `64` しかないので `iM` の場合は実質同じです。

2020-05-27 16:01 UTC, rhysd commented on wain-exec/src/cast.rs
> +            let gt_min = if MIN != MIN - 1.0 {
そうか，fraction の幅が対象より広ければ常に正確に表せるので成り立ちますね．unsigned の場合もおっしゃる通りでした．ありがとうございます．実質 `f64 → i32` の場合限定ですね

2020-05-27 16:01 UTC, rhysd approved these changes

2020-05-27 16:01 UTC, rhysd commented
ありがとうございます！

2020-05-27 16:01 UTC, merged