Fix binary parser and label stack behavior
rhysd/wain pull request #16
Opened 2020-05-26 10:15 UTC by kariya-mitsuru

Check input length before check version.
Check local variable count before expand types.
Push function's return type to label stack.

Passed new 77 tests. (but failed 7 new tests.)

**before**
```
End ".../wain/spec-test/wasm-testsuite/binary.wast":
  total: 85, passed: 17, failed: 1, skipped: 67

Results of 76 files:
  total: 19740, passed: 19046, failed: 498, skipped: 196
```

**after**
```
End ".../wain/spec-test/wasm-testsuite/binary.wast":
  total: 102, passed: 94, failed: 8, skipped: 0

Results of 76 files:
  total: 19757, passed: 19123, failed: 505, skipped: 129
```

2020-05-26 12:00 UTC, kariya-mitsuru commented
何でバイナリパーサの修正にラベルスタックの修正が入っているかと言うと、ラベルスタックの修正をしたら spec-test がバージョンチェックでパニックしたり、ローカル変数定義でコアダンプするようになったからです…
セクションサイズチェックは、スキップだったテストが実行されるようになってテスト失敗が増えてしまったからです…

2020-05-26 15:04 UTC, rhysd requested changes

2020-05-26 15:04 UTC, rhysd commented on wain-syntax-binary/src/parser.rs
> +        parser.check_len(4, "cannot get version")?;
このチェックってどうして必要なのでしょう？インプットが4バイト残っていない場合，次の match で `_` 側に入ってエラーになると思うのですが，それだとまずいでしょうか

2020-05-26 15:04 UTC, rhysd commented on wain-syntax-binary/src/parser.rs
> +            {
ここ含むいくつかの箇所でスコープを切ってますが，どういう意図でしょう？

2020-05-26 15:04 UTC, rhysd commented on wain-syntax-binary/src/parser.rs
> +        }
これは `locals_check` に一旦ローカル変数を確保しなくても良さそうです．

```rust
let mut locals = vec![];
let mut num_locals = 0u32;
for local in inner.parse_vec::<Locals>()? {
    let local = local?;
    if let Some(c) = count.checked_add(local.count) {
        locals.resize(locals.len() + loc.count as usize, loc.ty);
        count = c;
    } else {
        return Err(parser.error(ErrorKind::TooManyLocalVariables));
    }
}
```

2020-05-26 15:10 UTC, kariya-mitsuru commented on wain-syntax-binary/src/parser.rs
> +        parser.check_len(4, "cannot get version")?;
チェックしないとその後の `parser.input.try_into()` がエラーを返すので `unwrap()` でパニックを起こします。（起こしました

2020-05-26 15:14 UTC, kariya-mitsuru commented on wain-syntax-binary/src/parser.rs
> +            {
`parse_vec()` で返ってきた `vec` が `inner` をボロ―し続けるので `ensure_empty()` を呼べませんでした…
もしもっと正しい書き方があるのであれば教えて下さい…

2020-05-26 15:18 UTC, rhysd commented on wain-syntax-binary/src/parser.rs
> +            {
あー，確かに．`vec.parser.ensure_empty()` を使ってもらっても良いですが，現状でも OK です．

2020-05-26 15:19 UTC, kariya-mitsuru commented on wain-syntax-binary/src/parser.rs
> +        }
それがですね、spec-test のテストケースで 1 つ目のローカル変数型が `0xffff_ffff` 個あって、チェック前に `resize` しちゃうとコアダンプするんですよ…（2 つ目が 2 個あってチェックではエラーになる
で、テストを無事に終わらせるために仕方なくこの方式に変更したという…
テストを通すためにわざわざ変えるのも何だなぁ、とは思ったんですが…

2020-05-26 15:21 UTC, rhysd commented on wain-syntax-binary/src/parser.rs
> +        parser.check_len(4, "cannot get version")?;
なるほどっぐ… `unwrap` で4バイト読めないと引っかかりますね

2020-05-26 15:31 UTC, rhysd requested changes

2020-05-26 15:31 UTC, rhysd commented on wain-syntax-binary/src/parser.rs
> +        let mut locals = vec![];
```suggestion
        let mut locals = Vec::with_capacity(count as usize);
```

個数が分かってるので，最初に一気に確保しちゃってください

2020-05-26 15:33 UTC, rhysd commented on wain-syntax-binary/src/parser.rs
> +        }
そんな背景が… まあ実世界でも有り得ないわけではないですし，クラッシュは wain ではバグなので，対処は必須ですね．`loc.ty` は多分1バイトなのですが，0xffffffff バイト確保できないのですね…

2020-05-26 15:35 UTC, kariya-mitsuru commented on wain-syntax-binary/src/parser.rs
> +        let mut locals = vec![];
なるほど！

2020-05-26 16:14 UTC, kariya-mitsuru commented on wain-syntax-binary/src/parser.rs
> +        }
あっ、ウソ言ったかもしれないです…

2020-05-26 16:39 UTC, rhysd commented on wain-syntax-binary/src/parser.rs
> +        }
ぬ，何か勘違いありました？

2020-05-26 17:03 UTC, kariya-mitsuru commented on wain-syntax-binary/src/parser.rs
> +        }
イヌさんの思った通り、単にテストしてる環境でメモリが足りないだけっぽいです。悲しい…

2020-05-26 17:17 UTC, kariya-mitsuru commented on wain-syntax-binary/src/parser.rs
> +        }
と言う事で元のコメントに沿うように再度修正しました。

2020-05-27 02:12 UTC, rhysd commented on wain-syntax-binary/src/parser.rs
> +        }
ありがとうございます．お手数ですが，OOM でクラッシュしてしまうテストは手元で skip していただけると．

2020-05-27 02:13 UTC, rhysd approved these changes

2020-05-27 02:13 UTC, rhysd commented
ありがとうございます！

2020-05-27 02:13 UTC, merged