Fix TypeUse
rhysd/wain pull request #23
Opened 2020-05-31 14:50 UTC by kariya-mitsuru

Inline parameter and result declaration without typeidx should insert
type definition at the last of module.

Inline parameter and result declaration with typeidx should check
consistency.

Passed new 10 tests.

**before**
```
End ".../wain/spec-test/wasm-testsuite/func.wast":
  total: 130, passed: 124, failed: 6, skipped: 0

End ".../wain/spec-test/wasm-testsuite/call_indirect.wast":
  total: 153, passed: 149, failed: 4, skipped: 0

Results of 76 files:
  total: 19757, passed: 19416, failed: 212, skipped: 129
```

**after**
```
End ".../wain/spec-test/wasm-testsuite/func.wast":
  total: 130, passed: 130, failed: 0, skipped: 0

End ".../wain/spec-test/wasm-testsuite/call_indirect.wast":
  total: 153, passed: 153, failed: 0, skipped: 0

Results of 76 files:
  total: 19757, passed: 19426, failed: 202, skipped: 129
```

2020-05-31 17:43 UTC, rhysd requested changes

2020-05-31 17:43 UTC, rhysd commented on wain-syntax-text/src/wat2wasm.rs
> +        );
```rust
for type_def in self.types.iter() {
    ctx.types.push(type_def.ty.clone());
}
```

にしてもらえると，`.collect()` によるアロケーションが不要になりそうです

2020-05-31 17:43 UTC, rhysd commented on wain-syntax-text/src/parser.rs
> +    }
メソッド定義の前後は1行空白をあけておいていただけますでしょうか

2020-05-31 17:43 UTC, rhysd commented on wain-syntax-text/src/parser.rs
> +                None => RefOrInline::Inline(parser.create_inline_typeuse(start, &params, &results)),
これって inline というワードの使い方適切でしょうか？暗黙に自動で生成される ID は仕様では fresh id と呼ばれていたので，fresh のほうが良さそうに感じました

2020-05-31 17:43 UTC, rhysd commented on wain-syntax-text/src/wat2wasm.rs
> -                .collect::<Result<'_, _>>()?,
別に問題ないのですが，ここってどうして `params` と `results` を外に移したのでしょう？

2020-05-31 17:43 UTC, rhysd commented on wain-syntax-text/src/wat2wasm.rs
> +                wasm::InsnKind::CallIndirect(ctx.resolve_type_idx(&ty, start)?)
ここムーブして渡していただけますでしょうか？そうすれば `resolve_type_idx` は参照で受け取る必要がなく，したがって `resolve_index` も `Index` を参照で受け取る必要がなくなりそうです

2020-05-31 17:43 UTC, rhysd commented on wain-syntax-text/src/wat2wasm.rs
> +        tentatives: std::mem::replace(&mut parsed.module.tentatives, Vec::new()),
```suggestion
        tentatives: std::mem::take(&mut parsed.module.tentatives),
```

意味は同じですが，`take` でよりシンプルになりそうです

2020-05-31 17:43 UTC, rhysd commented on wain-syntax-text/src/parser.rs
> +    tentatives: Vec<TentativeTypeUse<'s>>,
tentative は temp と同じぐらい情報量が無いので，fresh_types または implicit_types とかでお願いできませんでしょうか？複数のソース（parser.rs と wat2wasm.rs）でまたがって使う値なので，なるべく説明的な変数名を付けておきたいです

2020-05-31 17:45 UTC, rhysd commented
ありがとうございます．

ちなみにこの fresh ID を後で解決しないといけないのって，type use に限らず table とか memory もそうですよね…

2020-06-01 01:59 UTC, rhysd requested changes

2020-06-01 01:59 UTC, rhysd commented on wain-syntax-text/src/wat2wasm.rs
> +                            .all(|(l, r)| l.ty == r.ty)
```suggestion
if ty.params
        .iter()
        .map(|p| p.ty)
        .eq(params.iter().map(|p| p.ty))
        && ty
            .results
            .iter()
            .map(|r| r.ty)
            .eq(results.iter().map(|r| r.ty))
```

`.eq()` を使うとシーケンスの長さをチェックする必要がなくなるので，よりシンプルになりそうです．

2020-06-01 04:55 UTC, kariya-mitsuru commented on wain-syntax-text/src/parser.rs
> +                None => RefOrInline::Inline(parser.create_inline_typeuse(start, &params, &results)),
inline は [spec](https://www.w3.org/TR/2019/REC-wasm-core-1-20191205/#text-format%E2%91%A0) で使用されている言葉です。
> A `typeuse` may also be replaced entirely by **inline** *parameter* and *result* declarations.

spec 上この構文要素（`typeuse`）では fresh id と言う用語は出てきません。

2020-06-01 05:13 UTC, kariya-mitsuru commented
> ちなみにこの fresh ID を後で解決しないといけないのって，type use に限らず table とか memory もそうですよね…

上のコメントにもリプライしましたが、`typeuse` では fresh ID は出てきません。
逆に、fresh ID の解決は（まだちゃんと確認してませんが）後である必要が無いと思います。

`typeuse` は以下の点で特殊だと思います。
- 型定義を自動挿入すべきかどうかはモジュールを最後まで見ないとわからない。
- 型定義を自動挿入する必要がある場合は、モジュールの最後に挿入する必要がある。

まぁ2点目は1点目の裏返しですが…

2020-06-01 05:20 UTC, kariya-mitsuru commented on wain-syntax-text/src/wat2wasm.rs
> +                            .all(|(l, r)| l.ty == r.ty)
ちなみに、`is_empty()` は省略できないので残しました。

2020-06-01 05:37 UTC, kariya-mitsuru commented on wain-syntax-text/src/wat2wasm.rs
> -                .collect::<Result<'_, _>>()?,
あ、すみません、ボロ―チェッカやデータの値確認とかで悪戦苦闘してた際に切り出したりしてたんですが、最終的に元の状態で上手くいくので戻します。

2020-06-01 05:52 UTC, rhysd commented on wain-syntax-text/src/wat2wasm.rs
> +                            .all(|(l, r)| l.ty == r.ty)
あっ，すみません，そうですね．僕の suggestion のほうが間違いです

2020-06-01 08:30 UTC, kariya-mitsuru commented on wain-syntax-text/src/parser.rs
> +    tentatives: Vec<TentativeTypeUse<'s>>,
用語 fresh は fresh id ではないのでミスリード、用語 implicit も、この時点では暗黙定義するとは限らない（単なる参照の場合がある）ので不適切と考えました。
ちなみに、tentative は C 言語では仮定義の意味で tentative definition と言うように使用します。今回のケースでは、C 言語では仮定義と同様、定義になる場合と単なる参照になる場合の両方があるためニュアンス的に合ってるなと思い、この用語を使用しました。

「何の？」に当たる部分が無いのはご指摘通りなので、tentative_types ではどうでしょうか？（「仮の」のニュアンスが欲しいな、と思いまして。ホントは tentative_type_definitions とかのほうがいいのかもしれませんが、流石に長すぎる気が…）
他に良い用語があればそれでも構いませんし、もちろんやはり fresh か implicit が良ければそちらにします。

2020-06-01 13:55 UTC, rhysd commented on wain-syntax-text/src/parser.rs
> +                None => RefOrInline::Inline(parser.create_inline_typeuse(start, &params, &results)),
> A typeuse may also be replaced entirely by inline parameter and result declarations.

この inline は parameter and result declarations にかかっているので，`(type 0 (param))` のように `param` が `type` 内に直接書かれているのを指して inline と書いてるのではないでしょうか？`typeuse` の index を省略した時を指して inline と書いているようには読めませんでした．

> spec 上この構文要素（typeuse） fresh id と言う用語は出てきません。

すみません，これは僕の勘違いでした．fresh identifier は function, memory, table, global だけですね．

2020-06-01 13:56 UTC, rhysd commented on wain-syntax-text/src/parser.rs
> +    tentatives: Vec<TentativeTypeUse<'s>>,
完全に好みの問題で申し訳ないですが，unresolved_type_uses が良いです！！

2020-06-01 14:12 UTC, rhysd commented on wain-syntax-text/src/parser.rs
> +    tentatives: Vec<TentativeTypeUse<'s>>,
`inserted_type_to_index` とかになるのかな… 一周回って kariya さん案の `tentative_types` のほうが簡潔で良い気もしてきました…（将来的にもっと良い名前を思い付いたらリファクタする感じで…）

2020-06-01 14:29 UTC, kariya-mitsuru commented on wain-syntax-text/src/parser.rs
> +                None => RefOrInline::Inline(parser.create_inline_typeuse(start, &params, &results)),
> この inline は parameter and result declarations にかかっているので，例えば `(type 0) (param)` の代わりに `param` が直接書かれているのを指して inline と書いてるのではないでしょうか？`typeuse` の index を省略した時を指して inline と書いているようには読めませんでした．

それはその通りです。
が、"`(type n)`" と "`(type n)` (`param`)\* (`result`)\*" のパターンと "(`param`)\* (`result`)\*" のパターンを区別する短くて良い単語が他に思い浮かばなかったので、型定義への**参照を含む**パターンを `Reference`（`param` と `result` は外側の `TypeUse` 構造体に含まれているのでそれ自身で有無を区別する必要が無い）、型定義への参照を含まず**インライン宣言のみ**のパターンを `Inline` 、と言う名称にしました。

とは言え、列挙型名の `RefOrInline` も含めてあまり良い名前とは思っていないので（あまり？）、何か良い命名があればさっくり直します。

2020-06-01 14:31 UTC, rhysd commented on wain-syntax-text/src/parser.rs
> +    tentatives: Vec<TentativeTypeUse<'s>>,
暗黙に指定されているという意味で implicit_types または implicit_type_uses が良いように思います

2020-06-01 14:46 UTC, kariya-mitsuru commented on wain-syntax-text/src/parser.rs
> +    tentatives: Vec<TentativeTypeUse<'s>>,
メンバ名は `implicit_type_uses`、構造体名も `ImplicitTypeUse` で修正しました。

2020-06-01 14:53 UTC, rhysd commented on wain-syntax-text/src/parser.rs
> +                None => RefOrInline::Inline(parser.create_inline_typeuse(start, &params, &results)),
下記に合わせて Implicit というのはどうでしょう？また enum の名前は僕も良いものが思い付かないのですが，明示するものと暗黙に挿入されるものの2種類があるという意味で TypeUseKind とかどうでしょう？

```rust
enum TypeUseKind<'s> {
    Explicit(Index<'s>),
    Implicit(u32),
}
```

2020-06-01 16:44 UTC, rhysd approved these changes
:100:

2020-06-01 16:44 UTC, rhysd commented
いつもありがとうございます！

2020-06-01 16:44 UTC, merged