Refactor CallFrame
rhysd/wain pull request #40
Opened 2020-07-09 15:47 UTC by kariya-mitsuru

2020-07-10 09:51 UTC, rhysd commented
簡単にで良いので、リファクタリングの概要と意図を書いてもらえませんでしょうか？10行未満ならコードだけでも良いのですが，少し長くなるとコードだけでは少し大変です．

2020-07-12 04:25 UTC, kariya-mitsuru commented
`CallFrame` に `&[ValType]` 型の `params` と `locals`  を持つ形になっていましたが、`params` の型情報は呼び出しの時点で既に `Stack.types` に存在する事、および、`locals` の型情報も `extend_from_slice` で追加していた事から、`CallFrame` に `params` と `locals` を持つことをやめて `Stack.types` を参照するように修正しました。

ホントは `CallFrame` 自体を `Stack` に持たせた方がスッキリするのですが、ちょっと修正量が多くなり過ぎる気がしたのでまずはここまでで止めています。

2020-07-13 14:09 UTC, rhysd commented
解説ありがとうございます．確かに `base_idx` があるので，Stack の `types` を見れば良いですね

2020-07-13 14:20 UTC, rhysd requested changes

2020-07-13 14:20 UTC, rhysd commented on wain-exec/src/stack.rs
> +    pub fn create_callframe(&mut self, params: &[ValType], locals: &[ValType]) -> CallFrame {
細かいですが，call frame で2単語なので名前は `create_call_frame` または `new_call_frame` でお願いします．

2020-07-13 14:21 UTC, rhysd commented
> ホントは CallFrame 自体を Stack に持たせた方がスッキリするのですが、ちょっと修正量が多くなり過ぎる気がしたのでまずはここまでで止めています。

確かにそっちのほうがきれいになりそうですね．もう作業されてたりします？もしまだなら，僕のほうでやってみようかなと．

2020-07-13 14:27 UTC, kariya-mitsuru commented on wain-exec/src/stack.rs
> +    pub fn create_callframe(&mut self, params: &[ValType], locals: &[ValType]) -> CallFrame {
修正しました！

2020-07-13 14:33 UTC, rhysd commented on wain-exec/src/stack.rs
> +    pub fn create_callframe(&mut self, params: &[ValType], locals: &[ValType]) -> CallFrame {
ありがとうございます🙏

2020-07-13 14:34 UTC, rhysd approved these changes

2020-07-13 14:34 UTC, merged

2020-07-13 14:37 UTC, kariya-mitsuru commented
ちょっと考え中でした。
`local_addr` 関数とかのアドレス（オフセット）を使う関数を `Stack` 内だけに閉じ込めた方がいいのかなぁ、とか考えてました…

2020-07-13 17:15 UTC, rhysd commented
では明日試しにコードいじってみます！