Small refactor for stack.rs
rhysd/wain pull request #51
Opened 2020-07-23 09:21 UTC by kariya-mitsuru

- `f32` & `f64` に対する不要な `use` declaration を削除しました。
- `Stack::frame` に対する不要な `pub` を削除しました。
- `Stack::bytes` に対するコメントを修正しました。
- `Stack::top::<Value>()` の替わりに `StackAccess::top()` を使用するようにしました。
- `TryFrom` に対する `use` declaration を削除しました。
- `Stack::types.len()` の替わりに `Stack::top_idx()` を使用するようにしました。
- `Stack::bytes.len()` の替わりに `Stack::top_addr()` を使用するようにしました。

2020-07-25 14:00 UTC, rhysd commented
> Stack::top::<Value>() の替わりに StackAccess::top() を使用するようにしました。

これは好みの問題もあると思いますが，`i32::top(self)` よりは `self.top::<i32>()` のほうが一般的な書き方で好ましいと思います

2020-07-25 14:00 UTC, rhysd requested changes

2020-07-25 14:00 UTC, rhysd commented on wain-exec/src/stack.rs
> +            ValType::F64 => self.write(addr, f64::top(self)),
この変更ってどういう意図でしょう？以前のほうがシンプルで良いように見えました

2020-07-25 14:00 UTC, rhysd commented on wain-exec/src/stack.rs
> +        <&'a [u8] as TryInto<T>>::Error: fmt::Debug,
`TryInto` を使うのはどうしてでしょう？ `TryFrom` のほうが `T::Error: fmt::Debug` とそのまま書けて良いと思いました

2020-07-26 02:47 UTC, kariya-mitsuru commented on wain-exec/src/stack.rs
> +            ValType::F64 => self.write(addr, f64::top(self)),
元の実装では `Stack::top::<Value>()` → `<Value as StackAccess>::top()` → `<xnn as StackAccess>::top()` で私にとっては認知的複雑度が高かったので修正しました。
`pub` を呼ばなくなったのも良いと思っています。
`read_local()` に合わせたという意味もあります。
特にそれ以上の意味は無いので、元のままでも全く問題ありません。（ただ、その場合は `read_local()` を修正した方がいいかも…）

2020-07-26 05:24 UTC, kariya-mitsuru commented on wain-exec/src/stack.rs
> +        <&'a [u8] as TryInto<T>>::Error: fmt::Debug,
元々は `try_into` なのに何で `TryFrom` が出てくるのかが分からなかった（無知）ので調べたのがきっかけです。
`T` の条件としては `try_into()` が出来る必要があるだけなので、ここで `TryFrom` を使用するのは制約がきつすぎるのかなぁ、と思いました。（`TryFrom` を満たしていれば自動的に `TryInto` が満たされるのは分かった＆ 今回の場合は必要な対象が `[u8; N]` なので完全に問題ないのですが…）
式の方を `T::try_from(&self.bytes[len..]).expect("top bytes")` に修正するというのも考えたのですが、`From` や `Into` のドキュメント見たら、使う側は `From` より `Into` 使った方がいいよ的な記載があったので、こちらも `TryInto` 使った方がいいのかなの思い、条件がちょっと鬱陶しい気はしたのですがこのように修正しました。

2020-07-26 05:28 UTC, kariya-mitsuru commented on wain-exec/src/stack.rs
> +        <&'a [u8] as TryInto<T>>::Error: fmt::Debug,
あ、別に元のままでも全く問題ありません。

2020-07-26 13:40 UTC, rhysd commented on wain-exec/src/stack.rs
> +            ValType::F64 => self.write(addr, f64::top(self)),
メソッド記法で定義している関数は，元のメソッド形式で呼び出すほうが良いかなぁと思います．

2020-07-26 13:41 UTC, rhysd commented on wain-exec/src/stack.rs
> +        <&'a [u8] as TryInto<T>>::Error: fmt::Debug,
where 句の条件が複雑になってしまっているので，元の TryFrom のままのほうが理解しやすいかなと思います．

2020-07-26 16:20 UTC, kariya-mitsuru commented on wain-exec/src/stack.rs
> +        <&'a [u8] as TryInto<T>>::Error: fmt::Debug,
了解しました。
`try_into` もそのままの方が良いでしょうか？

2020-07-26 16:23 UTC, kariya-mitsuru commented on wain-exec/src/stack.rs
> +            ValType::F64 => self.write(addr, f64::top(self)),
了解しました。

2020-07-27 13:17 UTC, rhysd commented on wain-exec/src/stack.rs
> +        <&'a [u8] as TryInto<T>>::Error: fmt::Debug,
はい，そのままで大丈夫です

2020-07-27 13:38 UTC, kariya-mitsuru commented on wain-exec/src/stack.rs
> +            ValType::F64 => self.write(addr, f64::top(self)),
あ、すみません、これは元の状態の方が良いという意味で良いでしょうか？
（`i32::top(self)` とかを `self.top::<i32>()` にするという意味ではなく）

2020-07-27 14:16 UTC, rhysd commented on wain-exec/src/stack.rs
> +            ValType::F64 => self.write(addr, f64::top(self)),
どちらでも良さそうですが， read_local に合わせるという意味では `self.top::<T>()` に変えていただくのが良さそうです

2020-07-28 12:21 UTC, rhysd approved these changes

2020-07-28 12:21 UTC, rhysd commented
ありがとうございます！

2020-07-28 12:21 UTC, merged