Refactor validate
rhysd/wain pull request #52
Opened 2020-07-24 07:49 UTC by kariya-mitsuru

バリデーションをちょっとリファクタリングしました。

`FuncBodyContext::op_stack` が `Vec<Type>` 型だったのですが、スタックに `Type::Unknown` が置かれるのは unreachable な時の現在のフレームのスタックの一番下にたかだか1つだけなので、`op_stack` の型を `Vec<ValType>` に変更して、`CtrlFrame::has_unknown` というフィールドを作りました。

2020-07-25 14:02 UTC, rhysd commented
確かにそうですね．改善ありがとうございます．ちょっと diff が大きめなので，明日確認させてください

2020-07-26 07:01 UTC, kariya-mitsuru commented
あぁ、すみません、もしかしたら `Type` の替わりに `Option<ValType>` 使うように修正する方がいいのかもしれないですね…
`Option<ValType>` だとメモリ使用量が `ValType` と変わらないので…

2020-07-26 07:12 UTC, kariya-mitsuru commented
`Option<ValType>` 使うとこんな感じです…
https://github.com/rhysd/wain/compare/master...kariya-mitsuru:refactor-validate2

2020-07-26 13:48 UTC, rhysd commented
あれ，メモリサイズの観点だと，元の `Type` も `Option<ValType>` も変わらない気がします．`Type` は variant の名前が違うだけで `Option<ValType>` とまったく同じ構造ですし…ちょっと確認してみます

2020-07-26 13:50 UTC, rhysd commented
`Vec<Type>` でも `Vec<Type>` でもメモリ使用量が変わらないなら，元の仕様にも載っているアルゴリズムに忠実な元実装で良いかなとちょっと思うのですが，どうでしょうか？この PR の実装（フラグを新たに追加してそっちで状態管理する実装）の利点ってありますでしょうか？

2020-07-26 15:56 UTC, kariya-mitsuru commented
あれ、ホンマや…
いや、何となく `ValType` -> `Type` の変換でメモリ使用量が減ったり型変換の手間が省かれたりするから速くなるかなぁ、と思ってやったら速くなったようだったので、てっきり予測が正しいのかと思ってました…
でもじゃあ何で速く成ってるんだろう…
手元ではこんな感じです。（何かあんまり安定しない感じですが、validationベンチはみんな速くなってるので…）
```
 name                                   master ns/iter  refactor-validate ns/iter  diff ns/iter   diff %  speedup
 example_benches::boyer_moore           2,765,558       2,806,999                        41,441    1.50%   x 0.99
 example_benches::brainfxxk             36,823,612      38,696,016                    1,872,404    5.08%   x 0.95
 example_benches::fib                   32,318,748      33,033,671                      714,923    2.21%   x 0.98
 example_benches::hello                 33,951          32,403                           -1,548   -4.56%   x 1.05
 example_benches::hello_global          34,129          32,789                           -1,340   -3.93%   x 1.04
 example_benches::hello_indirect_call   83,622          86,162                            2,540    3.04%   x 0.97
 example_benches::hello_struct          41,532          40,947                             -585   -1.41%   x 1.01
 example_benches::mandelbrot            405,704,547     411,637,541                   5,932,994    1.46%   x 0.99
 example_benches::mt19937               117,115,590     117,837,164                     721,574    0.62%   x 0.99
 example_benches::n_queens              11,497,471      11,788,723                      291,252    2.53%   x 0.98
 example_benches::nbodies               216,158,577     215,619,740                    -538,837   -0.25%   x 1.00
 example_benches::pi                    204,872,459     200,843,723                  -4,028,736   -1.97%   x 1.02
 example_benches::primes                605,804         611,617                           5,813    0.96%   x 0.99
 example_benches::quicksort             458,355         482,752                          24,397    5.32%   x 0.95
 example_benches::sqrt                  531,782         522,326                          -9,456   -1.78%   x 1.02
 example_benches::y_combinator          356,001         359,429                           3,428    0.96%   x 0.99
 parser_benches::binary::boyer_moore    115,511         114,575                            -936   -0.81%   x 1.01
 parser_benches::binary::brainfxxk      62,213          57,628                           -4,585   -7.37%   x 1.08
 parser_benches::binary::fib            16,196          16,554                              358    2.21%   x 0.98
 parser_benches::binary::guessing_game  42,840          40,788                           -2,052   -4.79%   x 1.05
 parser_benches::binary::mandelbrot     48,167          47,341                             -826   -1.71%   x 1.02
 parser_benches::binary::mt19937        163,500         156,061                          -7,439   -4.55%   x 1.05
 parser_benches::binary::n_queens       91,828          97,440                            5,612    6.11%   x 0.94
 parser_benches::binary::nbodies        134,741         138,197                           3,456    2.56%   x 0.97
 parser_benches::binary::pi             29,335          29,417                               82    0.28%   x 1.00
 parser_benches::binary::primes         34,048          34,334                              286    0.84%   x 0.99
 parser_benches::binary::quicksort      54,108          61,186                            7,078   13.08%   x 0.88
 parser_benches::binary::sqrt           47,282          45,740                           -1,542   -3.26%   x 1.03
 parser_benches::binary::y_combinator   22,225          28,458                            6,233   28.04%   x 0.78
 parser_benches::text::boyer_moore      783,096         805,332                          22,236    2.84%   x 0.97
 parser_benches::text::brainfxxk        469,573         479,208                           9,635    2.05%   x 0.98
 parser_benches::text::fib              97,234          97,408                              174    0.18%   x 1.00
 parser_benches::text::guessing_game    294,078         294,528                             450    0.15%   x 1.00
 parser_benches::text::mandelbrot       309,749         298,547                         -11,202   -3.62%   x 1.04
 parser_benches::text::mt19937          1,184,608       1,177,681                        -6,927   -0.58%   x 1.01
 parser_benches::text::n_queens         617,775         608,573                          -9,202   -1.49%   x 1.02
 parser_benches::text::nbodies          1,065,602       1,062,546                        -3,056   -0.29%   x 1.00
 parser_benches::text::pi               221,330         227,527                           6,197    2.80%   x 0.97
 parser_benches::text::primes           247,056         244,690                          -2,366   -0.96%   x 1.01
 parser_benches::text::quicksort        373,211         370,067                          -3,144   -0.84%   x 1.01
 parser_benches::text::sqrt             367,055         366,625                            -430   -0.12%   x 1.00
 parser_benches::text::y_combinator     166,602         164,106                          -2,496   -1.50%   x 1.02
 validation_benches::boyer_moore        30,067          29,860                             -207   -0.69%   x 1.01
 validation_benches::brainfxxk          15,722          14,490                           -1,232   -7.84%   x 1.09
 validation_benches::fib                3,589           3,301                              -288   -8.02%   x 1.09
 validation_benches::guessing_game      10,733          9,612                            -1,121  -10.44%   x 1.12
 validation_benches::mandelbrot         10,808          9,655                            -1,153  -10.67%   x 1.12
 validation_benches::mt19937            46,147          40,976                           -5,171  -11.21%   x 1.13
 validation_benches::n_queens           22,526          20,966                           -1,560   -6.93%   x 1.07
 validation_benches::nbodies            39,522          36,242                           -3,280   -8.30%   x 1.09
 validation_benches::pi                 8,535           7,762                              -773   -9.06%   x 1.10
 validation_benches::primes             9,215           8,360                              -855   -9.28%   x 1.10
 validation_benches::quicksort          14,145          13,085                           -1,060   -7.49%   x 1.08
 validation_benches::sqrt               13,913          12,408                           -1,505  -10.82%   x 1.12
 validation_benches::y_combinator       5,909           5,432                              -477   -8.07%   x 1.09
```

2020-07-26 15:57 UTC, kariya-mitsuru commented
ちなみに、`Option<ValType` 使った場合もこんな感じで速くなってるように思えます…
```
 name                                   master ns/iter  refactor-validate2 ns/iter  diff ns/iter   diff %  speedup
 example_benches::boyer_moore           2,765,558       2,768,083                          2,525    0.09%   x 1.00
 example_benches::brainfxxk             36,823,612      37,330,959                       507,347    1.38%   x 0.99
 example_benches::fib                   32,318,748      32,830,921                       512,173    1.58%   x 0.98
 example_benches::hello                 33,951          33,066                              -885   -2.61%   x 1.03
 example_benches::hello_global          34,129          34,162                                33    0.10%   x 1.00
 example_benches::hello_indirect_call   83,622          85,674                             2,052    2.45%   x 0.98
 example_benches::hello_struct          41,532          40,322                            -1,210   -2.91%   x 1.03
 example_benches::mandelbrot            405,704,547     417,400,933                   11,696,386    2.88%   x 0.97
 example_benches::mt19937               117,115,590     117,321,417                      205,827    0.18%   x 1.00
 example_benches::n_queens              11,497,471      11,596,034                        98,563    0.86%   x 0.99
 example_benches::nbodies               216,158,577     215,325,290                     -833,287   -0.39%   x 1.00
 example_benches::pi                    204,872,459     199,513,221                   -5,359,238   -2.62%   x 1.03
 example_benches::primes                605,804         597,644                           -8,160   -1.35%   x 1.01
 example_benches::quicksort             458,355         461,342                            2,987    0.65%   x 0.99
 example_benches::sqrt                  531,782         521,469                          -10,313   -1.94%   x 1.02
 example_benches::y_combinator          356,001         345,448                          -10,553   -2.96%   x 1.03
 parser_benches::binary::boyer_moore    115,511         106,083                           -9,428   -8.16%   x 1.09
 parser_benches::binary::brainfxxk      62,213          54,428                            -7,785  -12.51%   x 1.14
 parser_benches::binary::fib            16,196          14,643                            -1,553   -9.59%   x 1.11
 parser_benches::binary::guessing_game  42,840          38,866                            -3,974   -9.28%   x 1.10
 parser_benches::binary::mandelbrot     48,167          45,467                            -2,700   -5.61%   x 1.06
 parser_benches::binary::mt19937        163,500         150,803                          -12,697   -7.77%   x 1.08
 parser_benches::binary::n_queens       91,828          90,592                            -1,236   -1.35%   x 1.01
 parser_benches::binary::nbodies        134,741         132,961                           -1,780   -1.32%   x 1.01
 parser_benches::binary::pi             29,335          31,261                             1,926    6.57%   x 0.94
 parser_benches::binary::primes         34,048          30,241                            -3,807  -11.18%   x 1.13
 parser_benches::binary::quicksort      54,108          52,276                            -1,832   -3.39%   x 1.04
 parser_benches::binary::sqrt           47,282          47,585                               303    0.64%   x 0.99
 parser_benches::binary::y_combinator   22,225          23,881                             1,656    7.45%   x 0.93
 parser_benches::text::boyer_moore      783,096         770,476                          -12,620   -1.61%   x 1.02
 parser_benches::text::brainfxxk        469,573         478,272                            8,699    1.85%   x 0.98
 parser_benches::text::fib              97,234          100,366                            3,132    3.22%   x 0.97
 parser_benches::text::guessing_game    294,078         310,754                           16,676    5.67%   x 0.95
 parser_benches::text::mandelbrot       309,749         309,492                             -257   -0.08%   x 1.00
 parser_benches::text::mt19937          1,184,608       1,101,316                        -83,292   -7.03%   x 1.08
 parser_benches::text::n_queens         617,775         603,195                          -14,580   -2.36%   x 1.02
 parser_benches::text::nbodies          1,065,602       1,013,121                        -52,481   -4.93%   x 1.05
 parser_benches::text::pi               221,330         225,873                            4,543    2.05%   x 0.98
 parser_benches::text::primes           247,056         251,337                            4,281    1.73%   x 0.98
 parser_benches::text::quicksort        373,211         385,296                           12,085    3.24%   x 0.97
 parser_benches::text::sqrt             367,055         368,077                            1,022    0.28%   x 1.00
 parser_benches::text::y_combinator     166,602         169,838                            3,236    1.94%   x 0.98
 validation_benches::boyer_moore        30,067          28,012                            -2,055   -6.83%   x 1.07
 validation_benches::brainfxxk          15,722          14,868                              -854   -5.43%   x 1.06
 validation_benches::fib                3,589           3,361                               -228   -6.35%   x 1.07
 validation_benches::guessing_game      10,733          9,903                               -830   -7.73%   x 1.08
 validation_benches::mandelbrot         10,808          9,829                               -979   -9.06%   x 1.10
 validation_benches::mt19937            46,147          41,199                            -4,948  -10.72%   x 1.12
 validation_benches::n_queens           22,526          21,026                            -1,500   -6.66%   x 1.07
 validation_benches::nbodies            39,522          39,199                              -323   -0.82%   x 1.01
 validation_benches::pi                 8,535           8,138                               -397   -4.65%   x 1.05
 validation_benches::primes             9,215           8,592                               -623   -6.76%   x 1.07
 validation_benches::quicksort          14,145          13,242                              -903   -6.38%   x 1.07
 validation_benches::sqrt               13,913          12,534                            -1,379   -9.91%   x 1.11
 validation_benches::y_combinator       5,909           5,476                               -433   -7.33%   x 1.08
```

2020-07-26 16:32 UTC, kariya-mitsuru commented
ちょっと何が原因で速くなってるのか（あるいはホントは速くなってないのか）もうちょっと探ってみます。

2020-07-27 13:19 UTC, rhysd commented
ご確認ありがとうございます．なるほど速度変わるのですね．なんでだろう… 気になるのでちょっと僕の手元でもベンチマーク回してみます

2020-07-27 15:21 UTC, kariya-mitsuru commented
やはり `Vec` の型の違いによるのではなさそうでした。
`Vec<Type>` のまま他のリファクタリングしても速くなってました。

https://github.com/rhysd/wain/compare/master...kariya-mitsuru:refactor-validate3
```
 name                               master ns/iter  refactor-validate3 ns/iter  diff ns/iter   diff %  speedup
 validation_benches::boyer_moore    30,131          27,560                            -2,571   -8.53%   x 1.09
 validation_benches::brainfxxk      15,919          14,506                            -1,413   -8.88%   x 1.10
 validation_benches::fib            3,566           3,408                               -158   -4.43%   x 1.05
 validation_benches::guessing_game  10,913          10,131                              -782   -7.17%   x 1.08
 validation_benches::mandelbrot     10,975          10,111                              -864   -7.87%   x 1.09
 validation_benches::mt19937        46,779          42,842                            -3,937   -8.42%   x 1.09
 validation_benches::n_queens       23,743          21,967                            -1,776   -7.48%   x 1.08
 validation_benches::nbodies        39,942          38,310                            -1,632   -4.09%   x 1.04
 validation_benches::pi             8,580           7,812                               -768   -8.95%   x 1.10
 validation_benches::primes         9,219           8,380                               -839   -9.10%   x 1.10
 validation_benches::quicksort      14,780          13,014                            -1,766  -11.95%   x 1.14
 validation_benches::sqrt           13,553          12,383                            -1,170   -8.63%   x 1.09
 validation_benches::y_combinator   5,887           5,584                               -303   -5.15%   x 1.05
```

ただ、他のマシンでやったところ多少速くはなってましたがそこまでの差は出ませんでした…

2020-07-27 15:23 UTC, kariya-mitsuru commented
あ、あと一点バグが修正されてました…
[Fix ensure_op_stack_top behavior when the stack top is Type::Unknown](https://github.com/rhysd/wain/commit/33d130b60872ba223263e03f35b4c62017bbae00)

2020-07-31 12:27 UTC, rhysd commented
すみません，遅くなりましたが，確かに僕の手元でも速くなっていました :+1:

```
> cargo benchcmp master pr-52
 name                               master ns/iter  pr-52 ns/iter  diff ns/iter  diff %  speedup
 validation_benches::boyer_moore    21,922          20,680               -1,242  -5.67%   x 1.06
 validation_benches::brainfxxk      11,427          10,632                 -795  -6.96%   x 1.07
 validation_benches::fib            3,151           2,961                  -190  -6.03%   x 1.06
 validation_benches::guessing_game  7,747           7,348                  -399  -5.15%   x 1.05
 validation_benches::mandelbrot     8,014           7,254                  -760  -9.48%   x 1.10
 validation_benches::mt19937        29,857          29,067                 -790  -2.65%   x 1.03
 validation_benches::n_queens       15,750          14,803                 -947  -6.01%   x 1.06
 validation_benches::nbodies        26,981          25,419               -1,562  -5.79%   x 1.06
 validation_benches::pi             6,218           5,709                  -509  -8.19%   x 1.09
 validation_benches::primes         6,496           6,192                  -304  -4.68%   x 1.05
 validation_benches::quicksort      10,299          10,111                 -188  -1.83%   x 1.02
 validation_benches::sqrt           10,156          9,469                  -687  -6.76%   x 1.07
 validation_benches::y_combinator   5,102           4,873                  -229  -4.49%   x 1.05
```

2020-07-31 13:04 UTC, rhysd commented
おそらく，`has_known` フラグに書き換えることによる速度改善はわずかで，それ以外のどこかで大きく改善しているのだと思います．

2020-07-31 13:07 UTC, rhysd requested changes

2020-07-31 13:07 UTC, rhysd commented on wain-validate/src/insn.rs
> +    has_unknown: bool,
変更前のコードだと Type::Known と Type::Unknown の対だったので unknown で通用したのですが，変更後だと unknown だけだと何が unknown なのか分かりにくそうですね… ちょっと長いですが，`has_unknown_type` のほうが良いかなと思いました

2020-07-31 13:07 UTC, rhysd commented on wain-validate/src/insn.rs
> +        let actual = self.op_stack.len() + (if self.current_frame.has_unknown { 1 } else { 0 });
すみません，ここの `1` って何から来るのでしたっけ？ `Type::Unknown` を push してる分でしょうか

2020-08-02 01:52 UTC, kariya-mitsuru commented on wain-validate/src/insn.rs
> +        let actual = self.op_stack.len() + (if self.current_frame.has_unknown { 1 } else { 0 });
はい、その通りです。

2020-08-02 02:06 UTC, kariya-mitsuru commented on wain-validate/src/insn.rs
> +    has_unknown: bool,
修正しました！

2020-08-06 07:07 UTC, rhysd approved these changes
すみません、遅くなりました（マージし忘れてたとは言えない）。ありがとうございます！

2020-08-06 07:07 UTC, merged