Add support for sign extension instructions.
rhysd/wain pull request #58
Opened 2023-11-17 11:36 UTC by jmillikin

Proposal https://github.com/WebAssembly/sign-extension-ops added the following instructions for sign-extending integers:

    0xC0 i32.extend8_s
    0xC1 i32.extend16_s
    0xC2 i64.extend8_s
    0xC3 i64.extend16_s
    0xC4 i64.extend32_s

These instructions are now in widespread use, including in WASM generated by LLVM (e.g. when compiling Rust).

2023-11-17 18:23 UTC, rhysd requested changes
Can you add parsing text format of the instructions to wain-syntax-text crate?

2023-11-18 00:12 UTC, jmillikin commented
> Can you add parsing text format of the instructions to wain-syntax-text crate?

Done.

2023-11-18 02:57 UTC, rhysd approved these changes
Looks good. Thank you for this patch.

2023-11-18 03:02 UTC, rhysd commented
I'll fix clippy warnings locally.

2023-11-18 03:02 UTC, merged